### ISSUE TITLE
creation of service server failed for rosserial_tivac_tutorials/rgb_srv

### ISSUE THREAD

**Issue by altineller** [robosavvy/rosserial_tivac_tutorials#2]
Hello,

When I run the rgb_srv example, I get the following error from serial_node.py

I am on Ubuntu 18 with ROS melodic, but I also tested it with Ubuntu 16.04 with ROS kinetic, and for some reason it can not create the service server on ros side.

`can@rose:~$ rosrun rosserial_python serial_node.py _port:=/dev/ttyACM0 _baud:=57600
[INFO] [1542288687.044028]: ROS Serial Python Node
[INFO] [1542288687.047171]: Connecting to /dev/ttyACM0 at 57600 baud
[INFO] [1542288689.151538]: Requesting topics...
[INFO] [1542288689.926616]: Note: publish buffer size is 512 bytes
[ERROR] [1542288689.955049]: Creation of service server failed: rosserial_tivac_tutorials
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
`

**Comment by altineller** [comment]
This error too happens because the message files are not in path.

> cd ~/catkin_ws
> source devel/setup.bash 

solves the problem.

**Comment by Trushantadeshara** [comment]
I am facing different issue but in the rgb_srv itself.
It's giving me fatal error: rosserial_tivac_tutorials/ColorRGBA.h: No such file of directory. Any suggestions on how I can resolve this issue?
