### ISSUE TITLE
Unable to open USB device: LIBUSB_ERROR_ACCESS  Unable to find any ICDI devices

### ISSUE THREAD

**Issue by rishabhshah096** [robosavvy/rosserial_tivac_tutorials#5]
This error appears on giving the flash command of catkin_make
`catkin_make rosserial_tivac_tutorials_chatter_flash
`

**Comment by vmatos** [comment]
Are you able to see the device, through the command `lsusb`?

If yes, have you given all the necessary permissions to the user, to access the USB device?
[Setup device rules](http://wiki.ros.org/rosserial_tivac/Tutorials/TivaWare%20Setup#Get_the_flashing_tool)

**Comment by rishabhshah096** [comment]
This command works :
`sudo lm4flash gcc/blinky.bin
`
but this one `lm4flash gcc/blinky.bin
`
results into giving the above error

**Comment by vmatos** [comment]
Exactly, you have found the issue.

Now you can give the proper permissions for accessing the USB device.

You can use the provided guide as example on how to do it, or search on google.
